# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:shark_swim/animations/shark_swim_1/zzz/apply_frame {frame: 25}
scoreboard players add @s aj.shark_swim_1.frame 1