# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.shark_swim.root] run return 0
execute on passengers if entity @s[tag=aj.shark_swim.data] unless data entity @s {data:{rigHash: 'a91b83d3842c7580ceff7e8e8ba0fbc328b5032e2890eac429e194d9ed7a2294'}} on vehicle run function animated_java:shark_swim/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1