# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.shark_swim.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:shark_swim/as_root/pre_tick
execute if entity @s[tag=aj.shark_swim.animation.shark_swim_1.playing] run function animated_java:shark_swim/animations/shark_swim_1/zzz/on_tick
execute if entity @s[tag=aj.shark_swim.animation.shark_attack_raft.playing] run function animated_java:shark_swim/animations/shark_attack_raft/zzz/on_tick
execute if entity @s[tag=aj.shark_swim.animation.shark_swim_attack.playing] run function animated_java:shark_swim/animations/shark_swim_attack/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:shark_swim/as_root/post_tick