# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:shark_swim/animations/shark_attack_raft/zzz/apply_frame {frame: 25}
scoreboard players add @s aj.shark_attack_raft.frame 1