# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.tail_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.tail_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.tail_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.tail_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.tail_entire] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_entire set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.dorsal_fin] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_dorsal_fin set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.upper_jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upper_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.lower_jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lower_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.shark_swim.node.upper_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upper_body set from storage aj:uuid main.out