# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.shark_swim_1.frame dummy
scoreboard objectives add aj.shark_attack_raft.frame dummy
scoreboard objectives add aj.shark_swim_attack.frame dummy