# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.shark_swim.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'shark_swim', 'function_path': 'animated_java:shark_swim/animations/pause_all'}
tag @s remove aj.shark_swim.animation.shark_swim_1.playing
tag @s remove aj.shark_swim.animation.shark_attack_raft.playing
tag @s remove aj.shark_swim.animation.shark_swim_attack.playing