# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.shark_swim.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'shark_swim', 'function_path': 'animated_java:shark_swim/animations/shark_attack_raft/next_frame'}
execute if score @s aj.shark_attack_raft.frame matches 26.. run scoreboard players set @s aj.shark_attack_raft.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.shark_attack_raft.frame
execute at @s run function animated_java:shark_swim/animations/shark_attack_raft/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.shark_attack_raft.frame 1